### ISSUE TITLE
Which enclosure for OpenSprinkler?

### ISSUE THREAD

**Issue by mpfl** [nvonkorff/nvonkorff.github.io#2]
I'm planning to implement a (much) smaller retic system at my house controlled with an OpenSprinkler.

Are you able to tell me exactly which model box and internal panel you are using for your OpenSprinkler? I'm having a devil of a time trying to work it out yourself.

**Comment by nvonkorff** [comment]
Hey @mpfl - Sorry, only just saw this.
BUD Industries enclosure.
I got the idea from this forum, but that is for a bigger setup than I needed. https://opensprinkler.com/forums/topic/installation-in-custom-enclosure/
I ended up getting these from here:
https://www.digikey.com.au/product-detail/en/bud-industries/NBE-10563/377-1146-ND/387065
https://www.digikey.com.au/product-detail/en/bud-industries/NBX-10985-PL/377-1673-ND/2057388
