### ISSUE TITLE
just say hi

### ISSUE THREAD

**Issue by ExceptionCaught** [nvonkorff/nvonkorff.github.io#5]
hey Nick, Sorry for getting in touch with you via this weird way as Github do not have private message. 
I am going through exactly the same thing as you to use the opensprinkler, but just to replace my existing irrigation controller.
You setup is amazing. very neat. 
And I saw the same thread as you about that BUD enclosure, kinda cool. 
Good thing you mentioned about buying a smaller version. which I am going to do too.
My plan though, is to use a raspberry PI to control the opensprinkler via its api endpoint. 
happy to continue this conversation if you keen. my email. jonathon.wei-AT-gmail.com

**Comment by nvonkorff** [comment]
Catching up via email. Closing issue.
